name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.redmine }} ${{ matrix.db }} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '2.6', '3.0']
      fail-fast: false

    steps:
      - name: Checkout redmine_plugin_kit
        uses: actions/checkout@v2

      - name: Update package archives
        run: sudo apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          sudo apt-get install --yes --quiet
          build-essential
          cmake
          libicu-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Ruby dependencies
        run: |
          bundle install --jobs=4 --retry=3

      - name: Run RSpec
        env:
          RAILS_ENV: test
        run: bundle exec rspec
